<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //商品データ
        $data = [
            [
                "id" => 1,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールシュペリエル化粧水さっぱり',
                "price" => 3000,
            ],
            [
                "id" => 2,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールシュペリエル化粧水しっとり',
                "price" => 3000,
            ],
            [
                "id" => 3,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル乳液さっぱり',
                "price" => 3500,
            ],
            [
                "id" => 4,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル乳液しっとり',
                "price" => 3500,
            ],
            [
                "id" => 5,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル エンリッチドクリーム',
                "price" => 8000,
            ],
            [
                "id" => 6,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト　エンリッチドクリアクリーム',
                "price" => 8500,
            ],
            [
                "id" => 7,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールホワイト化粧水さっぱり',
                "price" => 3300,
            ],
            [
                "id" => 8,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールホワイト化粧水しっとり',
                "price" => 3300,
            ],
            [
                "id" => 9,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト乳液さっぱり',
                "price" => 3900,
            ],
            [
                "id" => 10,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト乳液しっとり',
                "price" => 3900,
            ],
            [
                "id" => 11,
                "manufacturer_id" => 1,
                "category_id" => 14,
                "name" => 'エリクシールシュペリエルエンリッチドセラム',
                "price" => 7500,
            ],
            [
                "id" => 12,
                "manufacturer_id" => 1,
                "category_id" => 14,
                "name" => 'エリクシールシュペリエルデザインタイムセラム',
                "price" => 4500,
            ],
            [
                "id" => 13,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'HAKU化粧水',
                "price" => 4500,
            ],
            [
                "id" => 14,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'HAKU乳液',
                "price" => 5000,
            ],
            [
                "id" => 15,
                "manufacturer_id" => 1,
                "category_id" => 6,
                "name" => 'HAKUメラノフォーカス',
                "price" => 10000,
            ],
            [
                "id" => 16,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-10',
                "price" => 4500,
            ],
            [
                "id" => 17,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-20',
                "price" => 4500,
            ],
            [
                "id" => 18,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-30',
                "price" => 4500,
            ],
            [
                "id" => 19,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-10',
                "price" => 3000,
            ],
            [
                "id" => 20,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-20',
                "price" => 3000,
            ],
            [
                "id" => 21,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-30',
                "price" => 3000,
            ],
            [
                "id" => 22,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックパウダリー ケース',
                "price" => 1000,
            ],
            [
                "id" => 23,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-10',
                "price" => 3200,
            ],
            [
                "id" => 24,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-20',
                "price" => 3200,
            ],
            [
                "id" => 25,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-30',
                "price" => 3200,
            ],
            [
                "id" => 26,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックライティングベース',
                "price" => 2600,
            ],
            [
                "id" => 27,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックスキンセンサーベース トーンアップ',
                "price" => 2600,
            ],
            [
                "id" => 28,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックスキンセンサーベース ナチュラル',
                "price" => 2600,
            ],
            [
                "id" => 29,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ RD606',
                "price" => 2800,
            ],
            [
                "id" => 30,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ BR505',
                "price" => 2800,
            ],
            [
                "id" => 31,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ BR707',
                "price" => 2800,
            ],
            [
                "id" => 32,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS RD332',
                "price" => 2800,
            ],
            [
                "id" => 33,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS BE233',
                "price" => 2800,
            ],
            [
                "id" => 34,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS BR734',
                "price" => 2800,
            ],
            [
                "id" => 35,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN PK340',
                "price" => 2800,
            ],
            [
                "id" => 36,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN RD300',
                "price" => 2800,
            ],
            [
                "id" => 37,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN RD582',
                "price" => 2800,
            ],
            [
                "id" => 38,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント RS500',
                "price" => 2300,
            ],
            [
                "id" => 39,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント PK301',
                "price" => 2300,
            ],
            [
                "id" => 40,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント RD302',
                "price" => 2300,
            ],
            [
                "id" => 41,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュドラマティックムードヴェール PK200',
                "price" => 3500,
            ],
            [
                "id" => 42,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュドラマティックムードヴェール RD100',
                "price" => 3500,
            ],
            [
                "id" => 43,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）RS314',
                "price" => 1800,
            ],
            [
                "id" => 44,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）PK313',
                "price" => 1800,
            ],
            [
                "id" => 45,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）RD312',
                "price" => 1800,
            ],
            [
                "id" => 46,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー ケース',
                "price" => 1000,
            ],
            [
                "id" => 47,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュアイブロウ用ホルダー',
                "price" => 900,
            ],
            [
                "id" => 48,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）BR611',
                "price" => 900,
            ],
            [
                "id" => 49,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）BR711',
                "price" => 900,
            ],
            [
                "id" => 50,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）GY921',
                "price" => 900,
            ],
            [
                "id" => 51,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）BR611',
                "price" => 900,
            ],
            [
                "id" => 52,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）BR711',
                "price" => 900,
            ],
            [
                "id" => 53,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）GY921',
                "price" => 900,
            ],
            [
                "id" => 54,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）50',
                "price" => 1800,
            ],
            [
                "id" => 55,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）60',
                "price" => 1800,
            ],
            [
                "id" => 56,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）70',
                "price" => 1800,
            ],
            [
                "id" => 57,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュロングステイアイライナーN（カートリッジ）BR662',
                "price" => 1200,
            ],
            [
                "id" => 58,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュロングステイアイライナーN（カートリッジ）BK999',
                "price" => 1200,
            ],
            [
                "id" => 59,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュアイライナー＆ブロー用ホルダーN',
                "price" => 900,
            ],
            [
                "id" => 60,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュパーフェクトブラックライナー BK999',
                "price" => 2500,
            ],
            [
                "id" => 61,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュフルビジョンマスカラ（ボリューム） BK970',
                "price" => 2800,
            ],
            [
                "id" => 62,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュビューティーシルエットマスカラ BK999',
                "price" => 2800,
            ],
            [
                "id" => 63,
                "manufacturer_id" => 5,
                "category_id" => 1,
                "name" => 'オバジメイク落とし',
                "price" => 2800,
            ],
        ];

         DB::table('items')->insert($data);
    }
}

