<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //商品データ
        $data = [
            [
                "id" => 1,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールシュペリエル化粧水さっぱり',
                "price" => 3000,
            ],
            [
                "id" => 2,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールシュペリエル化粧水しっとり',
                "price" => 3000,
            ],
            [
                "id" => 3,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル乳液さっぱり',
                "price" => 3500,
            ],
            [
                "id" => 4,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル乳液しっとり',
                "price" => 3500,
            ],
            [
                "id" => 5,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールシュペリエル エンリッチドクリーム',
                "price" => 8000,
            ],
            [
                "id" => 6,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト　エンリッチドクリアクリーム',
                "price" => 8500,
            ],
            [
                "id" => 7,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールホワイト化粧水さっぱり',
                "price" => 3300,
            ],
            [
                "id" => 8,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'エリクシールホワイト化粧水しっとり',
                "price" => 3300,
            ],
            [
                "id" => 9,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト乳液さっぱり',
                "price" => 3900,
            ],
            [
                "id" => 10,
                "manufacturer_id" => 1,
                "category_id" => 4,
                "name" => 'エリクシールホワイト乳液しっとり',
                "price" => 3900,
            ],
            [
                "id" => 11,
                "manufacturer_id" => 1,
                "category_id" => 14,
                "name" => 'エリクシールシュペリエルエンリッチドセラム',
                "price" => 7500,
            ],
            [
                "id" => 12,
                "manufacturer_id" => 1,
                "category_id" => 14,
                "name" => 'エリクシールシュペリエルデザインタイムセラム',
                "price" => 4500,
            ],
            [
                "id" => 13,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'HAKU化粧水',
                "price" => 4500,
            ],
            [
                "id" => 14,
                "manufacturer_id" => 1,
                "category_id" => 3,
                "name" => 'HAKU乳液',
                "price" => 5000,
            ],
            [
                "id" => 15,
                "manufacturer_id" => 1,
                "category_id" => 6,
                "name" => 'HAKUメラノフォーカス',
                "price" => 10000,
            ],
            [
                "id" => 16,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-10',
                "price" => 4500,
            ],
            [
                "id" => 17,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-20',
                "price" => 4500,
            ],
            [
                "id" => 18,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'HAKU薬用美白美容液ファンデーション OC-30',
                "price" => 4500,
            ],
            [
                "id" => 19,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-10',
                "price" => 3000,
            ],
            [
                "id" => 20,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-20',
                "price" => 3000,
            ],
            [
                "id" => 21,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックパウダリー OC-30',
                "price" => 3000,
            ],
            [
                "id" => 22,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックパウダリー ケース',
                "price" => 1000,
            ],
            [
                "id" => 23,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-10',
                "price" => 3200,
            ],
            [
                "id" => 24,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-20',
                "price" => 3200,
            ],
            [
                "id" => 25,
                "manufacturer_id" => 1,
                "category_id" => 7,
                "name" => 'マキアージュドラマティックエッセンスリキッド OC-30',
                "price" => 3200,
            ],
            [
                "id" => 26,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックライティングベース',
                "price" => 2600,
            ],
            [
                "id" => 27,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックスキンセンサーベース トーンアップ',
                "price" => 2600,
            ],
            [
                "id" => 28,
                "manufacturer_id" => 1,
                "category_id" => 8,
                "name" => 'マキアージュドラマティックスキンセンサーベース ナチュラル',
                "price" => 2600,
            ],
            [
                "id" => 29,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ RD606',
                "price" => 2800,
            ],
            [
                "id" => 30,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ BR505',
                "price" => 2800,
            ],
            [
                "id" => 31,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズ BR707',
                "price" => 2800,
            ],
            [
                "id" => 32,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS RD332',
                "price" => 2800,
            ],
            [
                "id" => 33,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS BE233',
                "price" => 2800,
            ],
            [
                "id" => 34,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュドラマティックスタイリングアイズS BR734',
                "price" => 2800,
            ],
            [
                "id" => 35,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN PK340',
                "price" => 2800,
            ],
            [
                "id" => 36,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN RD300',
                "price" => 2800,
            ],
            [
                "id" => 37,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックルージュN RD582',
                "price" => 2800,
            ],
            [
                "id" => 38,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント RS500',
                "price" => 2300,
            ],
            [
                "id" => 39,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント PK301',
                "price" => 2300,
            ],
            [
                "id" => 40,
                "manufacturer_id" => 1,
                "category_id" => 11,
                "name" => 'マキアージュドラマティックリップティント RD302',
                "price" => 2300,
            ],
            [
                "id" => 41,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュドラマティックムードヴェール PK200',
                "price" => 3500,
            ],
            [
                "id" => 42,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュドラマティックムードヴェール RD100',
                "price" => 3500,
            ],
            [
                "id" => 43,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）RS314',
                "price" => 1800,
            ],
            [
                "id" => 44,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）PK313',
                "price" => 1800,
            ],
            [
                "id" => 45,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー（レフィル）RD312',
                "price" => 1800,
            ],
            [
                "id" => 46,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュチークカラー ケース',
                "price" => 1000,
            ],
            [
                "id" => 47,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュアイブロウ用ホルダー',
                "price" => 900,
            ],
            [
                "id" => 48,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）BR611',
                "price" => 900,
            ],
            [
                "id" => 49,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）BR711',
                "price" => 900,
            ],
            [
                "id" => 50,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（ペンシル）GY921',
                "price" => 900,
            ],
            [
                "id" => 51,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）BR611',
                "price" => 900,
            ],
            [
                "id" => 52,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）BR711',
                "price" => 900,
            ],
            [
                "id" => 53,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュダブルブロークリエーター（パウダー）GY921',
                "price" => 900,
            ],
            [
                "id" => 54,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）50',
                "price" => 1800,
            ],
            [
                "id" => 55,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）60',
                "price" => 1800,
            ],
            [
                "id" => 56,
                "manufacturer_id" => 1,
                "category_id" => 10,
                "name" => 'マキアージュアイブロースタイリング３D（レフィル）70',
                "price" => 1800,
            ],
            [
                "id" => 57,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュロングステイアイライナーN（カートリッジ）BR662',
                "price" => 1200,
            ],
            [
                "id" => 58,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュロングステイアイライナーN（カートリッジ）BK999',
                "price" => 1200,
            ],
            [
                "id" => 59,
                "manufacturer_id" => 1,
                "category_id" => 12,
                "name" => 'マキアージュアイライナー＆ブロー用ホルダーN',
                "price" => 900,
            ],
            [
                "id" => 60,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュパーフェクトブラックライナー BK999',
                "price" => 2500,
            ],
            [
                "id" => 61,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュフルビジョンマスカラ（ボリューム） BK970',
                "price" => 2800,
            ],
            [
                "id" => 62,
                "manufacturer_id" => 1,
                "category_id" => 9,
                "name" => 'マキアージュビューティーシルエットマスカラ BK999',
                "price" => 2800,
            ],
            [
                "id" => 63,
                "manufacturer_id" => 5,
                "category_id" => 1,
                "name" => 'オバジXミルククレンジング',
                "price" => 3500,
            ],
            [
                "id" => 64,
                "manufacturer_id" => 5,
                "category_id" => 2,
                "name" => 'オバジXブーストムースウォッシュ',
                "price" => 3000,
            ],
            [
                "id" => 65,
                "manufacturer_id" => 5,
                "category_id" => 3,
                "name" => 'オバジXリフトローション',
                "price" => 5000,
            ],
            [
                "id" => 66,
                "manufacturer_id" => 5,
                "category_id" => 4,
                "name" => 'オバジXリフトエマルジョン',
                "price" => 5000,
            ],
            [
                "id" => 67,
                "manufacturer_id" => 5,
                "category_id" => 1,
                "name" => 'オバジアクティブベースクレンジング',
                "price" => 2500,
            ],
            [
                "id" => 68,
                "manufacturer_id" => 5,
                "category_id" => 2,
                "name" => 'オバジアクティブベースウォッシュ',
                "price" => 2500,
            ],
            [
                "id" => 69,
                "manufacturer_id" => 5,
                "category_id" => 3,
                "name" => 'オバジアクティブベースローション',
                "price" => 3500,
            ],
            [
                "id" => 70,
                "manufacturer_id" => 5,
                "category_id" => 4,
                "name" => 'オバジアクティブベースミルク',
                "price" => 3500,
            ],
            [
                "id" => 71,
                "manufacturer_id" => 5,
                "category_id" => 15,
                "name" => 'オバジピーリングV10エッセンス',
                "price" => 5000,
            ],
            [
                "id" => 72,
                "manufacturer_id" => 5,
                "category_id" => 15,
                "name" => 'オバジピーリングV10エッセンス',
                "price" => 5000,
            ],
            [
                "id" => 73,
                "manufacturer_id" => 5,
                "category_id" => 16,
                "name" => 'オバジCセラムゲル',
                "price" => 4000,
            ],
            [
                "id" => 74,
                "manufacturer_id" => 5,
                "category_id" => 5,
                "name" => 'オバジCマルチプロテクトUV',
                "price" => 3000,
            ],
            [
                "id" => 75,
                "manufacturer_id" => 5,
                "category_id" => 6,
                "name" => 'オバジC25セラムネオ',
                "price" => 10000,
            ],
            [
                "id" => 76,
                "manufacturer_id" => 5,
                "category_id" => 6,
                "name" => 'オバジC20セラム',
                "price" => 8000,
            ],
            [
                "id" => 77,
                "manufacturer_id" => 5,
                "category_id" => 6,
                "name" => 'オバジC10セラム（レギュラー）',
                "price" => 4000,
            ],
            [
                "id" => 78,
                "manufacturer_id" => 5,
                "category_id" => 14,
                "name" => 'オバジダーマパワーXステムリフトセラム（レギュラー）',
                "price" => 5000,
            ],
            [
                "id" => 79,
                "manufacturer_id" => 5,
                "category_id" => 4,
                "name" => 'オバジダーマパワーXステムリフトクリーム',
                "price" => 10000,
            ],
            [
                "id" => 80,
                "manufacturer_id" => 5,
                "category_id" => 14,
                "name" => 'オバジダーマパワーXステムシャープアイ',
                "price" => 6000,
            ],
            [
                "id" => 81,
                "manufacturer_id" => 5,
                "category_id" => 7,
                "name" => 'オバジCセラムファンデーション OC-10',
                "price" => 3000,
            ],
            [
                "id" => 82,
                "manufacturer_id" => 5,
                "category_id" => 7,
                "name" => 'オバジCセラムファンデーション OC-20',
                "price" => 3000,
            ],
            [
                "id" => 83,
                "manufacturer_id" => 5,
                "category_id" => 7,
                "name" => 'オバジCセラムファンデーション OC-30',
                "price" => 3000,
            ],
            [
                "id" => 84,
                "manufacturer_id" => 5,
                "category_id" => 8,
                "name" => 'オバジCブライトキープベースUV',
                "price" => 3000,
            ],
            [
                "id" => 85,
                "manufacturer_id" => 5,
                "category_id" => 8,
                "name" => 'オバジクリアフェイスパウダー',
                "price" => 3500,
            ],
            [
                "id" => 86,
                "manufacturer_id" => 2,
                "category_id" => 1,
                "name" => 'DEWクレンジングオイル',
                "price" => 2500,
            ],
            [
                "id" => 87,
                "manufacturer_id" => 2,
                "category_id" => 1,
                "name" => 'DEWクレンジングクリーム',
                "price" => 2500,
            ],
            [
                "id" => 88,
                "manufacturer_id" => 2,
                "category_id" => 2,
                "name" => 'DEWクリームソープ',
                "price" => 2500,
            ],
            [
                "id" => 89,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'DEW化粧水 さっぱり',
                "price" => 3500,
            ],
            [
                "id" => 90,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'DEW化粧水 しっとり',
                "price" => 3500,
            ],
            [
                "id" => 91,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEW乳液 しっとり',
                "price" => 3800,
            ],
            [
                "id" => 92,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEW乳液 さっぱり',
                "price" => 3800,
            ],
            [
                "id" => 93,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEWクリーム',
                "price" => 5000,
            ],
            [
                "id" => 94,
                "manufacturer_id" => 2,
                "category_id" => 14,
                "name" => 'DEWモイストリフトエッセンス',
                "price" => 5800,
            ],
            [
                "id" => 95,
                "manufacturer_id" => 2,
                "category_id" => 5,
                "name" => 'DEW UVデイエッセンス',
                "price" => 3000,
            ],
            [
                "id" => 96,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'DEW ブライトニング化粧水 さっぱり',
                "price" => 4000,
            ],
            [
                "id" => 97,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'DEW ブライトニング化粧水 しっとり',
                "price" => 4000,
            ],
            [
                "id" => 98,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEW ブライトニング乳液 さっぱり',
                "price" => 4300,
            ],
            [
                "id" => 99,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEW ブライトニング乳液 しっとり',
                "price" => 4300,
            ],
            [
                "id" => 100,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'DEW ブライトニングクリーム',
                "price" => 5500,
            ],
            [
                "id" => 101,
                "manufacturer_id" => 2,
                "category_id" => 5,
                "name" => 'DEW ブライトニングUVデイエッセンス',
                "price" => 3500,
            ],
            [
                "id" => 102,
                "manufacturer_id" => 2,
                "category_id" => 2,
                "name" => 'スイサイ 酵素洗顔パウダー 32個',
                "price" => 1800,
            ],
            [
                "id" => 103,
                "manufacturer_id" => 2,
                "category_id" => 2,
                "name" => 'スイサイ 洗顔料',
                "price" => 1800,
            ],
            [
                "id" => 104,
                "manufacturer_id" => 2,
                "category_id" => 1,
                "name" => 'スイサイ ジェリークレンジング',
                "price" => 2400,
            ],
            [
                "id" => 105,
                "manufacturer_id" => 2,
                "category_id" => 1,
                "name" => 'スイサイ ジェリークレンジング',
                "price" => 2400,
            ],
            [
                "id" => 106,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'スイサイ ローションさっぱり',
                "price" => 2100,
            ],
            [
                "id" => 107,
                "manufacturer_id" => 2,
                "category_id" => 3,
                "name" => 'スイサイ ローションしっとり',
                "price" => 2100,
            ],
            [
                "id" => 108,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'スイサイ エマルジョンさっぱり',
                "price" => 2100,
            ],
            [
                "id" => 109,
                "manufacturer_id" => 2,
                "category_id" => 4,
                "name" => 'スイサイ エマルジョンしっとり',
                "price" => 2100,
            ],
            [
                "id" => 110,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドール パウダレスウェット OC-B',
                "price" => 2800,
            ],
            [
                "id" => 111,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドール パウダレスウェット OC-C',
                "price" => 2800,
            ],
            [
                "id" => 113,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドール パウダレスウェット OC-D',
                "price" => 2800,
            ],
            [
                "id" => 114,
                "manufacturer_id" => 2,
                "category_id" => 8,
                "name" => 'コフレドール パクト用ケースc',
                "price" => 1000,
            ],
            [
                "id" => 115,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドールリフォルムグロウ リクイドUV OC-B',
                "price" => 3500,
            ],
            [
                "id" => 116,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドールリフォルムグロウ リクイドUV OC-C',
                "price" => 3500,
            ],
            [
                "id" => 117,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドールリフォルムグロウ リクイドUV OC-D',
                "price" => 3500,
            ],
            [
                "id" => 118,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドールスキンイリュージョンプライマーUV',
                "price" => 2800,
            ],
            [
                "id" => 119,
                "manufacturer_id" => 2,
                "category_id" => 7,
                "name" => 'コフレドールモイスチャーグロウベースUV',
                "price" => 2800,
            ],
            [
                "id" => 120,
                "manufacturer_id" => 2,
                "category_id" => 8,
                "name" => 'ミラノコレクション本体',
                "price" => 9000,
            ],
            [
                "id" => 121,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールスキンシンクロルージュ PK316',
                "price" => 2700,
            ],
            [
                "id" => 122,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールスキンシンクロルージュ RS341',
                "price" => 2700,
            ],
            [
                "id" => 123,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールスキンシンクロルージュ BE240',
                "price" => 2700,
            ],
            [
                "id" => 124,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールスキンシンクロルージュ PK317',
                "price" => 2700,
            ],
            [
                "id" => 125,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールコントゥアリップデュオ 01',
                "price" => 2800,
            ],
            [
                "id" => 126,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールコントゥアリップデュオ 02',
                "price" => 2800,
            ],
            [
                "id" => 127,
                "manufacturer_id" => 2,
                "category_id" => 11,
                "name" => 'コフレドールコントゥアリップデュオ 03',
                "price" => 2800,
            ],
            [
                "id" => 128,
                "manufacturer_id" => 2,
                "category_id" => 10,
                "name" => 'コフレドールWブロウデザイナー BR-47',
                "price" => 2600,
            ],
            [
                "id" => 129,
                "manufacturer_id" => 2,
                "category_id" => 10,
                "name" => 'コフレドールWブロウデザイナー BR-48',
                "price" => 2600,
            ],
            [
                "id" => 130,
                "manufacturer_id" => 2,
                "category_id" => 10,
                "name" => 'コフレドールWブロウデザイナー GY-19',
                "price" => 2600,
            ],
            [
                "id" => 131,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールヌーディインプレッションアイズ01',
                "price" => 2800,
            ],
            [
                "id" => 132,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールヌーディインプレッションアイズ02',
                "price" => 2800,
            ],
            [
                "id" => 133,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールヌーディインプレッションアイズ03',
                "price" => 2800,
            ],
            [
                "id" => 134,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールビューティオーラアイズ01',
                "price" => 3500,
            ],
            [
                "id" => 135,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールビューティオーラアイズ02',
                "price" => 3500,
            ],
            [
                "id" => 136,
                "manufacturer_id" => 2,
                "category_id" => 9,
                "name" => 'コフレドールビューティオーラアイズ03',
                "price" => 3500,
            ],
            [
                "id" => 137,
                "manufacturer_id" => 2,
                "category_id" => 12,
                "name" => 'コフレドールスマイルアップチークスS 01',
                "price" => 2300,
            ],
            [
                "id" => 138,
                "manufacturer_id" => 2,
                "category_id" => 12,
                "name" => 'コフレドールスマイルアップチークスS 02',
                "price" => 2300,
            ],
            [
                "id" => 139,
                "manufacturer_id" => 2,
                "category_id" => 12,
                "name" => 'コフレドールスマイルアップチークスS 03',
                "price" => 2300,
            ],
            [
                "id" => 140,
                "manufacturer_id" => 3,
                "category_id" => 3,
                "name" => 'ルシェリリンクルリペアローション',
                "price" => 3500,
            ],
            [
                "id" => 141,
                "manufacturer_id" => 3,
                "category_id" => 4,
                "name" => 'ルシェリリンクルリペアエマルジョン',
                "price" => 3800,
            ],
            [
                "id" => 142,
                "manufacturer_id" => 3,
                "category_id" => 5,
                "name" => 'ルシェリリンクルホワイトUVエマルジョン',
                "price" => 3100,
            ],
            [
                "id" => 143,
                "manufacturer_id" => 3,
                "category_id" => 4,
                "name" => 'ルシェリリンクルリペアナイトクリーム',
                "price" => 5000,
            ],
            [
                "id" => 144,
                "manufacturer_id" => 3,
                "category_id" => 1,
                "name" => 'ルシェリオイルクレンジングジェル',
                "price" => 2500,
            ],
            [
                "id" => 145,
                "manufacturer_id" => 3,
                "category_id" => 1,
                "name" => 'ルシェリ酵素クレンジングオイル',
                "price" => 2500,
            ],
            [
                "id" => 146,
                "manufacturer_id" => 3,
                "category_id" => 2,
                "name" => 'ルシェリクリームウォッシュ',
                "price" => 2200,
            ],
            [
                "id" => 147,
                "manufacturer_id" => 3,
                "category_id" => 13,
                "name" => 'ONE BY KOSE セラムヴェール（レギュラー）',
                "price" => 5000,
            ],
            [
                "id" => 148,
                "manufacturer_id" => 3,
                "category_id" => 6,
                "name" => 'ONE BY KOSE メラノショットホワイト（レギュラー）',
                "price" => 5300,
            ],
            [
                "id" => 149,
                "manufacturer_id" => 3,
                "category_id" => 14,
                "name" => 'ONE BY KOSE ザリンクレス（レギュラー）',
                "price" => 5800,
            ],
            [
                "id" => 150,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットパクト 405',
                "price" => 2800,
            ],
            [
                "id" => 151,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットパクト 410',
                "price" => 2800,
            ],
            [
                "id" => 152,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットパクト 415',
                "price" => 2800,
            ],
            [
                "id" => 153,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットリキッド 405',
                "price" => 3200,
            ],
            [
                "id" => 154,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットリキッド 410',
                "price" => 3200,
            ],
            [
                "id" => 155,
                "manufacturer_id" => 3,
                "category_id" => 7,
                "name" => 'エスプリークシンクロフィットリキッド 415',
                "price" => 3200,
            ],
            [
                "id" => 156,
                "manufacturer_id" => 3,
                "category_id" => 11,
                "name" => 'エスプリークプライムティントルージュ RD452',
                "price" => 2300,
            ],
            [
                "id" => 157,
                "manufacturer_id" => 3,
                "category_id" => 11,
                "name" => 'エスプリークプライムティントルージュ RO652',
                "price" => 2300,
            ],
            [
                "id" => 158,
                "manufacturer_id" => 3,
                "category_id" => 11,
                "name" => 'エスプリークプライムティントルージュ PK856',
                "price" => 2300,
            ],
            [
                "id" => 159,
                "manufacturer_id" => 3,
                "category_id" => 11,
                "name" => 'エスプリークプライムティントルージュ OR250',
                "price" => 2300,
            ],
            [
                "id" => 160,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（ペンシル＆パウダー）BR301',
                "price" => 2100,
            ],
            [
                "id" => 161,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（ペンシル＆パウダー）BR300',
                "price" => 2100,
            ],
            [
                "id" => 184,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（ペンシル＆パウダー）GY002',
                "price" => 2100,
            ],
            [
                "id" => 162,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（リキッド＆パウダー）BR301',
                "price" => 2100,
            ],
            [
                "id" => 163,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（リキッド＆パウダー）BR300',
                "price" => 2100,
            ],
            [
                "id" => 164,
                "manufacturer_id" => 3,
                "category_id" => 10,
                "name" => 'エスプリークWアイブロウ（リキッド＆パウダー）GY002',
                "price" => 2100,
            ],
            [
                "id" => 165,
                "manufacturer_id" => 3,
                "category_id" => 12,
                "name" => 'エスプリークピュアリーベールチーク（レフィル） PK-2c',
                "price" => 1300,
            ],
            [
                "id" => 166,
                "manufacturer_id" => 3,
                "category_id" => 12,
                "name" => 'エスプリークピュアリーベールチーク（レフィル） PK-3c',
                "price" => 1300,
            ],
            [
                "id" => 167,
                "manufacturer_id" => 3,
                "category_id" => 12,
                "name" => 'エスプリークピュアリーベールチーク（レフィル） OR-4c',
                "price" => 1300,
            ],
            [
                "id" => 168,
                "manufacturer_id" => 4,
                "category_id" => 15,
                "name" => 'ソフィーナiPベースケアセラム',
                "price" => 5000,
            ],
            [
                "id" => 169,
                "manufacturer_id" => 4,
                "category_id" => 2,
                "name" => 'ソフィーナiP炭酸洗顔料',
                "price" => 3000,
            ],
            [
                "id" => 170,
                "manufacturer_id" => 4,
                "category_id" => 5,
                "name" => 'ソフィーナiP UVレジスト（リッチクリーム）',
                "price" => 3000,
            ],
            [
                "id" => 171,
                "manufacturer_id" => 4,
                "category_id" => 5,
                "name" => 'ソフィーナiP UVレジスト（スムースミルク）',
                "price" => 3000,
            ],
            [
                "id" => 172,
                "manufacturer_id" => 4,
                "category_id" => 3,
                "name" => 'ソフィーナボーテ高保湿化粧水　しっとり',
                "price" => 2700,
            ],
            [
                "id" => 173,
                "manufacturer_id" => 4,
                "category_id" => 3,
                "name" => 'ソフィーナボーテ高保湿化粧水　とてもしっとり',
                "price" => 2700,
            ],
            [
                "id" => 185,
                "manufacturer_id" => 4,
                "category_id" => 3,
                "name" => 'ソフィーナボーテ美白化粧水　しっとり',
                "price" => 3000,
            ],
            [
                "id" => 186,
                "manufacturer_id" => 4,
                "category_id" => 3,
                "name" => 'ソフィーナボーテ美白化粧水　とてもしっとり',
                "price" => 3000,
            ],
            [
                "id" => 174,
                "manufacturer_id" => 4,
                "category_id" => 4,
                "name" => 'ソフィーナボーテ高保湿乳液　しっとり',
                "price" => 3200,
            ],
            [
                "id" => 175,
                "manufacturer_id" => 4,
                "category_id" => 4,
                "name" => 'ソフィーナボーテ高保湿乳液　とてもしっとり',
                "price" => 3200,
            ],
            [
                "id" => 176,
                "manufacturer_id" => 4,
                "category_id" => 4,
                "name" => 'ソフィーナボーテ美白乳液　しっとり',
                "price" => 3500,
            ],
            [
                "id" => 177,
                "manufacturer_id" => 4,
                "category_id" => 4,
                "name" => 'ソフィーナボーテ美白乳液　とてもしっとり',
                "price" => 3500,
            ],
            [
                "id" => 178,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタパウダーファンデーション　OC-03',
                "price" => 2800,
            ],
            [
                "id" => 179,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタパウダーファンデーション　OC-05',
                "price" => 2800,
            ],
            [
                "id" => 180,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタパウダーファンデーション　OC-07',
                "price" => 2800,
            ],
            [
                "id" => 181,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタナチュラルグロウラスティングリキッド　OC-03',
                "price" => 3200,
            ],
            [
                "id" => 182,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタナチュラルグロウラスティングリキッド　OC-05',
                "price" => 3200,
            ],
            [
                "id" => 183,
                "manufacturer_id" => 4,
                "category_id" => 7,
                "name" => 'プリマヴィスタナチュラルグロウラスティングリキッド　OC-07',
                "price" => 3200,
            ],
            [
                "id" => 187,
                "manufacturer_id" => 4,
                "category_id" => 8,
                "name" => 'プリマヴィスタ化粧崩れ防止用下地',
                "price" => 2800,
            ],
        ];

         DB::table('items')->insert($data);
    }
}

